spring:
  # 项目名称
  application:
    name: user-center
  # 数据库配置
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/javaproduct?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/javaproduct
    username: root
    password: qwert
  # Session 失效时间设置
  session:
    timeout: 86400

# 项目端口号
server:
  port: 8080
  servlet:
    # 添加全局路径
    context-path: /api
  max-http-header-size: 8192
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 逻辑字段
      logic-delete-value: 1 # 逻辑未删除值(默认为1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为0)